---
title: "Introduction to `DyadBoot`"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to `DyadBoot`}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Introduction

`DyadBoot` provides tools for dyadic random bootstrapping and analysis.
It is indicated for experimental data involving dyads, in which effects want to 
be explored at the individual level. 

-Example-

Original Data

Dyad_id	Individual	Treatment	    Body mass (g)
Trial1	  100	     High protein     	0.5
Trial1	  101	     Low protein      	0.433
Trial2  	102	     Low protein      	0.552
Trial2	  103	     High protein	      0.601
Trial3	  104	     High protein	      0.342
Trial3	  105	     Low protein	      0.56

With DyadBoot::randOne, DyadBoot::randMult or DyadBoot::randBoot

Dyad_id	focal_Individual	opposite_Individual	focal_Treatment	opposite_Treatment	focal_Body_Size	opposite_Body_Size
Trial1	    100	                101	           High protein	     Low protein	         0.5	           0.433
Trial2	    102	                103	           Low protein	     High protein	         0.552	         0.601
Trial3	    104	                105	           High protein	     Low protein	         0.342	         0.56



Installation

You can install the package from GitHub using `devtools`:
```{r setup}

#install.packages("devtools")
#devtools::install_github("toomanycrickets/DyadBoot")

```


Functions: 

1. 'randBoot' - Randomly assigns the role of "focal" and "opposite" to each individual of each dyad. Bootstrapping is then performed on the chosen model (package only supports lm, glm, lmer, and glmer so far). The random assignment of "focal" and "ooposite" roles occurs at every iteration of the bootstrapping to mitigate random sampling bias. The output includes  "results$bootstrap_results", a string of all summary tables from each bootstrapping iteration, and "results$anova_results", a string of all Anova tables from each bootstrapping iteration.

model_formula <- dependent_variable ~ independent_variable #specify model formula. It takes the format generated by the randBoot function with the "focal" and "opposite" roles attributed. Example: model_formula <- focal_aggression ~ opposite_mass

results <- DyadBoot::randBoot(data = data,
                           dyad_id_col = "dyad_id",
                           model_formula = model_formula,
                           model_type = "lm",
                           n_bootstraps = 1000,
                           focal_cols = c("dependent_variable"), 
                           opposite_cols = c("dependent_variable"))

#"focal_cols" and "opposite_cols" both take the original name of the variable, without the attribution of "focal" or "opposite". Must be same variable. 
Example: (...) focal_cols = c("aggression"), 
               opposite_cols = c("aggression"))
               
results$bootstrap_results #for list of all summary(model) performed in the bootstrapping
results$anova_results #for list of all car::Anova(model) performed in the bootstrapping


__________________________
2. 'randOne' - To only perform the random assignment of roles without performing the bootstrapping step. Returns a dataset called "focal_opposite_data". Useful for testing model assumptions before analysis.

focal_opposite_data <- DyadBoot::randOne(data = data, dyad_id_col = "your_dyad_column_name")



__________________________
3. 'randMult' - To perform the random assignment of roles a specified number of times without performing the bootstrapping step. Returns a list with all datasets.

resultsMult <- randMult(data, dyad_id_col = "your_dyad_column_name", num_iterations = number_of_iterations_desired)

resultsMult$results_list #access all datasets



__________________________
4. 'repDataSet' - Takes 'randMult' output as input and chooses the most representative dataset for the particular variables specified (whereby the mean for that dataset is closest to the overall mean of all datasets generated by randMult). Also provides a dataframe that contains the mean for the categorical variable of interested for all its levels - for all datasets (the number of rows in this dataframe is the number of datasets. The number of columns is the number of levels of the categorical variable)

rep_data<- DyadBoot::repDataSet(resultsMult, "numerical_variable", "categorical_variable")

rep_data$closest_data #access most representative dataset
rep_data$each_dataset_means #access dataframe with means for each level of the categorical variable for each dataset generated by randMult


__________________________
5. 'averages' - Takes the output of DyadBoot::randBoot as input and returns a table with the averages of all coeficients (e.g. estimate, standard error, z-value, p-value) (for each tested factor) from all iterations of the bootstrapping. Also provides standard errors of these averages).

DyadBoot::averages(results$bootstrap_results)



__________________________
6. 'anovaPvals' - Extracts all P-values from the Anova output generated by DyadBoot::randBoot (results$anova_results) for the specified factor.

pvals<-DyadBoot::anovaPvals(results$anova_results, "factor_name")



__________________________
7. 'MeanOfMeans' - Calculates the overall mean of all bootstrap iterations of a specified numerical variable for all levels of a specified categorical variable.

overall_means <- DyadBoot::MeanOfMeans(each_dataset_means) #each_dataset_means is one of the outputs of DyadBoot::repDataSet, a dataframe that contains the mean for the categorical variable of interested for all its levels - for each dataset generated by DyadBoot::randMult. 



__________________________
8. 'histMeans' - Histogram of distribution of means for specified level of specified categorical variable.

histMeans(each_dataset_means, numerical_variable, categorical_variable, level) #each_dataset_means is one of the outputs of DyadBoot::repDataSet, a dataframe that contains the mean for the categorical variable of interested for all its levels (can be accessed via rep_data$each_dataset_means) - for each dataset generated by DyadBoot::randMult. 


__________________________
9. 'histPvals' - Histogram of the distribution of all p-values for the selected factor. Text within the plot specifies the number of iterations that the selected factor had a significant p-value.

DyadBoot::histPvals(results$bootstrap_results, coeff_name = "your_coefficient_name")


__________________________
10. - 'plotBoot' - Two grid plot. Left grid -raincloud plot (with boxplot) of the most representative dataset with overlay of overall mean for the specified variable. Right grid - Histogram of pvalues with red dashed line at 0.05.

rainplot<-DyadBoot::plotBoot(rep_data$closest_data, "numerical_variable", "categorical_variable", overall_means = overall_means_object, #output of fucntion DyadBoot::MeanOfMeans
               xlab_name = "name", ylab_name = "name", main_title = "name", p_values = pvals #list of p-values of factor of interested, output of DyadBoot::anovaPvals.
               )
               
rainplot #to generate plot




---
